# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 04:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Additional data with user-/developer-defined significance.', verbose_name='meta data'),
        ),
    ]
