# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_message_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='meta',
        ),
        migrations.AddField(
            model_name='message',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='data'),
        ),
    ]
