# Generated by Django 5.0.6 on 2024-06-03 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_messages", "0002_alter_message_index_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="message",
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                models.F("user"), models.F("delivered_at"), name="user_delivered_at"
            ),
        ),
    ]
